# syntax=docker/dockerfile:1

FROM azavea/cicero:spacy-cpu0

RUN mkdir -p /train-on-batch/output && mkdir -p /train/output
WORKDIR /train

COPY spacy-wrapper-cpu.sh /train/spacy-wrapper-cpu.sh

## set up wandb
RUN ["wandb", "login", "YOUR_OWN_WANDB_KEY"]

ENTRYPOINT ["/train/spacy-wrapper-cpu.sh"]
