# syntax=docker/dockerfile:1

FROM azavea/cicero:spacy-gpu0

RUN mkdir -p /train-on-batch/output && mkdir -p /train/output
WORKDIR /train

COPY ./address /train/address
COPY ./email /train/email
COPY spacy-wrapper-gpu.sh /train/spacy-wrapper-gpu.sh

## set up wandb
RUN ["wandb", "login", "1b07bca30600e9459ea297f08870c2f3da0c4c52"]
RUN ["wandb", "offline"]

ENTRYPOINT ["/train/spacy-wrapper-gpu.sh"]
